version: '3.8'
services:
  backend:
    build: ./g-scores-be
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/exam_db
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exam_db
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: