source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'rails', '~> 7.0.8'
gem 'pg', '~> 1.5'
gem 'puma', '~> 5.0'
gem 'active_model_serializers', '~> 0.10.14'
gem 'sidekiq', '~> 7.3'
gem 'sidekiq-scheduler', '~> 5.0'
gem 'sendgrid-actionmailer', '~> 3.2'
gem 'csv', '~> 3.3'
gem 'rack-cors', '~> 2.0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'logger', '~> 1.6'
gem 'sprockets-rails'
gem 'dotenv-rails'
gem 'rack-protection'
gem 'redis', '~> 5.0'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.4'
end

group :development do
  gem 'letter_opener', '~> 1.10'
end